# Generated by Django 4.1 on 2022-10-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("option_one", models.CharField(max_length=200)),
                ("option_two", models.CharField(max_length=200)),
                ("option_three", models.CharField(max_length=200)),
                ("option_four", models.CharField(max_length=200)),
                ("option_five", models.CharField(max_length=200)),
                ("option_six", models.CharField(max_length=200)),
                ("option_two_count", models.IntegerField(default=0)),
                ("option_three_count", models.IntegerField(default=0)),
                ("option_four_count", models.IntegerField(default=0)),
                ("option_five_count", models.IntegerField(default=0)),
                ("option_six_count", models.IntegerField(default=0)),
                ("option_one_count", models.IntegerField(default=0)),
            ],
        ),
    ]
