# Generated by Django 4.1 on 2022-10-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_post_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="slug",),
    ]
