# Generated by Django 4.1 on 2022-10-06 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
