# Generated by Django 4.1 on 2022-10-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_post_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pic",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
