# Generated by Django 4.1 on 2022-10-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_post_pic"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="pic",),
    ]
