# Generated by Django 4.1 on 2022-10-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0010_posts_rate_delete_post_posts_stars"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=200)),
                ("massage", models.TextField(blank=True, default="")),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.group"
                    ),
                ),
                (
                    "stars",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.rate"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Socity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("socity", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(name="Posts",),
        migrations.AddField(
            model_name="post",
            name="to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="post.socity"
            ),
        ),
    ]
